spring.datasource.url=jdbc:mysql://localhost:3306/growgenie?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
growgenie.jwtSecret=growgenieSecretKeyForJWTAuthentication2026ModernArchitecture
growgenie.jwtExpirationMs=864000000

# Groq API
groq.api.key=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

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adzitech@gmail.com
spring.mail.password=vvmq zgxs rfaq oeqt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

server.port=8080
